{{- if or .Values.gateway.token .Values.gateway.encryptionKey }}
{{- if and (not .Values.gateway.existingTokenSecret) (not .Values.gateway.existingEncryptionKeySecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goclaw.fullname" . }}-gateway
  labels:
    {{- include "goclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.gateway.token }}
  GOCLAW_GATEWAY_TOKEN: {{ .Values.gateway.token | quote }}
  {{- end }}
  {{- if .Values.gateway.encryptionKey }}
  GOCLAW_ENCRYPTION_KEY: {{ .Values.gateway.encryptionKey | quote }}
  {{- end }}
{{- end }}
{{- end }}
